//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15
use migration::sea_orm;
use sea_orm::{entity::prelude::*, Set};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use validator::Validate;
use chrono::NaiveDateTime as DateTime;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub first_name: String,
    pub last_name: String,
    pub login_token: Option<String>,
    pub login_sent_at: Option<String>,
    pub reset_token: Option<String>,
    pub reset_sent_at: Option<DateTime>,
    pub email_verification_token: Option<String>,
    pub email_verification_sent_at: Option<DateTime>,
    pub email_verified_at: Option<DateTime>,
    pub status: Status
}

#[derive(EnumIter, DeriveActiveEnum, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "String(Some(1))")]
pub enum Status {
    #[sea_orm(string_value = "A")]
    Active,
    #[sea_orm(string_value = "D")]
    Deleted,
}


#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

#[derive(Debug, Validate, Deserialize)]
pub struct Validator {
    #[validate(length(min = 2, message = "Name must be at least 2 characters long."))]
    pub first_name: String,
    #[validate(length(min = 2, message = "Name must be at least 2 characters long."))]
    pub last_name: String,
    #[validate(email)]
    pub email: String,
}


impl ActiveModel {
    fn validator(&self) -> Validator {
        Validator {
            first_name: self.first_name.as_ref().to_owned(),
            last_name: self.last_name.as_ref().to_owned(),
            email: self.email.as_ref().to_owned(),
        }
    }
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        let validator = self.validator();
        let validator_res = validator.validate();
        if let Err(e) = validator_res {
            return Err(DbErr::Custom(e.to_string()));
        }
        if insert {
            let mut this = self;
            this.pid = Set(Uuid::new_v4());
            Ok(this)
        } else {
            Ok(self)
        }
    }
}
